# Generated by Django 5.1.2 on 2024-11-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_course', models.CharField(max_length=100, verbose_name='Título')),
                ('description_course', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('archive_course', models.FileField(upload_to='materiais_curso/', verbose_name='Arquivo')),
                ('archive_course_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('ppt', 'PowerPoint')], max_length=5, verbose_name='Tipo de Arquivo')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
            ],
        ),
    ]
